# https://github.com/Koihik/LuaFormatter/blob/master/docs/Style-Config.md
column_limit: 80
indent_width: 2
use_tab: false
keep_simple_control_block_one_line: true
keep_simple_function_one_line: true
continuation_indent_width: 2
align_args: false
break_after_functioncall_lp: false
break_before_functioncall_rp: false
align_parameter: false
chop_down_parameter: true
break_after_functiondef_lp: false
break_before_functiondef_rp: false
align_table_field: true
break_after_table_lb: true
break_before_table_rb: true
chop_down_table: true
chop_down_kv_table: true
column_table_limit: 80
table_sep: ','
extra_sep_at_table_end: true
break_after_operator: false
double_quote_to_single_quote: false
spaces_before_call: 1

